Carbon:
  Image:
    loader: '<i class="loader" aria-hidden="true"></i>'
    outputDimensions: true
    async: false
    inlineSVG: false
    allowCropping: false
    allowUpScaling: false
    width: false
    height: false
    maximumWidth: 2560
    maximumHeight: 2560
    dummy:
      ratio: 1.3333333333 # 4:3
      color: '#f0ad4e'
      image:
        width: 100%
        height: 0
        background: 'no-repeat 50%'
        background-size: contain
      background:
        background: 'no-repeat 50%'
        background-size: contain
    srcset:
      - 1
      - 2
    lightbox:
      rel: noopener
      class: lightbox
      target: _blank
      async: false
      allowCropping: false
      allowUpScaling: false
      width: false
      height: false
      maximumWidth: 2560
      maximumHeight: 2560
      preset: false

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Carbon.Image:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Carbon.Image: true
  Fusion:
    defaultContext:
      'Carbon.Image.Asset': 'Carbon\Image\Fusion\AssetHelper'
