Carbon:
  Image:
    outputDimensions: true
    async: false
    inlineSVG: false
    allowCropping: false
    allowUpScaling: false
    maximumWidth: 2560
    maximumHeight: 2560
    dummy:
      ratio: 1.3333333333 # 4:3
      color: '#f0ad4e'
      image:
        width: 100%
        height: 0
        background: 'no-repeat 50%'
        background-size: contain
      background:
        background: 'no-repeat 50%'
        background-size: contain
    srcset:
      - 1
      - 2
    lightbox:
      rel: noopener
      class: lightbox
      target: _blank
      async: false
      allowCropping: false
      allowUpScaling: false
      width: false
      height: false
      maximumWidth: 2560
      maximumHeight: 2560
      preset: false
    responsive:
      loader: '<i class="loader" aria-hidden="true"></i>'
      placeholderWidth: 96
      maximumScreenDensity: 2
      sizesPresets:
        - 96
        - 160
        - 320
        - 480
        - 640
        - 960
        - 1024
        - 1440
        - 1920
        - 2560
        - 3840
        - 5120

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Carbon.Image:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Carbon.Image: true
  Fusion:
    defaultContext:
      'Carbon.Image.Asset': 'Carbon\Image\Fusion\AssetHelper'
