Carbon:
  Image:
    inlineSVG: false
    lazy:
      enabled: false
      lazyWidth: null
      class: lazyload
    minMaxImageSize:
      min: 300
      max: 3900
      # If you set this to null, the steps generation gets deactivated
      step: 150
      multiplicator: [2, 1.5, 1, 0.75, 0.5, 0.25]

    alternativeText:
      # You can set the language mapping like that:
      # languageMapping:
      #   en: 0
      #   de: 1
      #   fr: 2
      languageMapping: null
      splitCharacter: '||'
      property: caption
    dummy:
      forgroundColor: fff
      backgroundColor: 999
      force: false
    lightbox:
      rel: noopener
      class: 'lightbox'
      target: _blank
      width: 2560
      height: null
      thumbnailPreset: null
      variantPreset: null
